[package]
name = "yarad"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version="2.33.3", features=["yaml"] }
daemonize = "0.4.1"
env_logger = "0.9.0"
libc = "0.2.98"
log = "0.4.14"
nix = "0.22.0"
no-panic = "0.1.15"
parse_int = "0.5.0"
serde = {version="1.0.126", features=["derive"] }
serde_yaml = "0.8.17"
username = "0.2.0"
yara = "0.6.1"
