# log level [error|warn|info|debug|trace]
log_level: warn 
local_socket: /var/run/yarad/yarad.ctl
local_socket_group: yarad
local_socket_mode: 0o666
rules_dir: /var/lib/yarad/rules
working_dir: /var/run/yarad
user: yarad
auto_recompile_rules: true
