name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TARGET_DIR: ${{ github.workspace }}/target
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache CARGO_HOME
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-home-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}
      - name: Setup Rust toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: Run cargo-make
        run: cargo make ci
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache CARGO_HOME
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-home-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}
      - name: Setup Rust toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Install cargo-outdated
        run: cargo install cargo-outdated
      - name: Run cargo-audit
        run: cargo audit
      - name: Run cargo-deny check licenses
        run: cargo deny check licenses
      - name: Run cargo-deny check bans
        run: cargo deny check bans
      - name: Run cargo-deny check advisories
        run: cargo deny check advisories
      - name: Run cargo-outdated
        run: cargo outdated -R
